# Pandas Styling

In [2]:
import pandas as pd
import numpy as np

np.random.seed(88)
df = pd.DataFrame({'A': np.linspace(1,10,10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10,4), columns=list('BCDE'))],
               axis=1)
df.iloc[3,3] = np.nan
df.iloc[0,2] = np.nan

In [3]:
print(df)

      A         B         C         D         E
0   1.0  0.106884       NaN  0.956563  0.068411
1   2.0  1.068514  0.997183 -0.931548  0.730430
2   3.0 -0.171214 -1.288691  1.061436 -0.040501
3   4.0 -0.903721 -1.554133       NaN  0.200526
4   5.0 -0.747329  1.068081 -0.277024  0.086557
5   6.0 -0.253221 -1.212041  0.277273  0.552219
6   7.0 -0.467743 -1.427493  0.885805  2.360634
7   8.0 -1.522006 -0.215945  0.190327  0.722256
8   9.0 -0.870716  0.101749  0.555358  0.962261
9  10.0  1.433499 -0.701818 -0.856952 -0.858158

In [4]:
# 최대/최소값 하이라이트

df.style.highlight_max(color='green').highlight_min(color='pink')

In [5]:
df.style.highlight_null()

In [6]:
df.style.highlight_null(null_color='violet')

In [7]:
df.style.set_na_rep("OutofScope").highlight_null(null_color="orange")

<ipython-input-7-91f5fd7ca8d8>:1: FutureWarning: this method is deprecated in favour of `Styler.format(na_rep=..)`
  df.style.set_na_rep("OutofScope").highlight_null(null_color="orange")

In [8]:
# Heatmap

df.style.background_gradient()

In [9]:
# Table Properties

df.style.set_properties(**{'border': '2.0px solid green',
                           'color': 'magenta'})

In [11]:
# Bar Chart

df.style.bar(color='green')

In [13]:
# add caption
df.style.set_caption("This is Dataframe styling demo")

In [14]:
# 인덱스/컬럼 숨기기
df.style.hide_index()
df.style.hide_columns('B')

In [15]:
# 데이터 표시
df.style.format("{:.3%}", na_rep="&&")